#!/usr/bin/env node

const shell = require("shelljs") // eslint-disable-line
const chalk = require("chalk") // eslint-disable-line
const exec  = require("child_process").exec

process.stdin.resume()
process.stdin.setEncoding("utf8")

process.stdout.write("\nCleaning old repository")

cleanRepo(() => {
    exec("git init", () => {
        process.stdout.write("\nDone!")
        process.exit(0)
    })
})

function cleanRepo(callback) {
    shell.rm("-rf", ".git/")
    addCheckMark(callback)
}

function addCheckMark(callback) {
    process.stdout.write(chalk.green(" ✓"))
    if (callback) callback()
}
