#!/usr/bin/env node

const shell = require("shelljs") // eslint-disable-line
const chalk = require("chalk") // eslint-disable-line
const exec  = require("child_process").exec
const path  = require("path")
const fs    = require("fs")

process.stdin.resume()
process.stdin.setEncoding("utf8")

process.stdout.write("\nCleaning old repository")

cleanRepo(() => {
    initGit(() => {
        process.stdout.write("\nDone!")
        process.exit(0)
    })
})

function cleanRepo(callback) {
    shell.rm("-rf", ".git/")
    deleteFileInCurrentDir("setup", () => {
        addCheckMark()
        callback()
    })
}

function initGit(callback) {
    exec("git init && git add . && git commit -m \"Initial commit\"", callback)
}

function addCheckMark() {
    process.stdout.write(chalk.green(" ✓"))
}

function deleteFileInCurrentDir(file, callback) {
    fs.unlink(path.join(__dirname, file), callback)
}
